export const ADD_INGREDIANT = 'ADD_INGREDIANT'
export const REMOVE_INGREDIANT = 'REMOVE_INGREDIANT'
export const SET_INGREDIANTS = 'SET_INGREDIANT'
export const FETCH_INGREDIANT_FAILED = 'FETCH_INGREDIANT_FAILED' 

export const PURCHASE_BARGER_START = 'PURCHASE_BARGER_START'
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS'
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL'

export const PURCHASE_INIT = 'PURCHASE_INIT'