export const ADD_INGREDIANT = 'ADD_INGREDIANT'
export const REMOVE_INGREDIANT = 'REMOVE_INGREDIANT'
export const SET_INGREDIANTS = 'SET_INGREDIANT'
export const FETCH_INGREDIANT_FAILED = 'FETCH_INGREDIANT_FAILED' 
